Feature/print fwsig
wirenboard/wb-mcu-fw-flasher pull request #26
Opened 2024-04-04 21:36 UTC by vdromanov

Пользователи виндавса страдают при необходимости узнать fw-sig => сделали ключик --get-fw-sig

Основной затык - ux вокруг всяких переходов в бутлоадер c/без сохранения настроечек (+ неизвестное состояние при запуске)

вроде получилось все обойти:
![image](https://github.com/wirenboard/wb-mcu-fw-flasher/assets/25829054/01c35ead-f253-4bb1-978a-4cbf2fd1ed71)

на виндавсе еще не тыкал

2024-04-05 07:08 UTC, pgasheev commented
А можно не переходя в бутлодер считать сигнатуру? Я из скриншота не очень понял.

Ну и ещё накину, если можно: может добавить ещё чтение версии прошивки и версии загрузчика? А то простого способа их прочитать также нет. При этом версия прошивки доступна только из прошивки. Если девайс в загрузчике, можно вместо неё написать, что перейдите в прошивку для чтения версии прошивки. Ну и ключ назвать --get-dev-info или как-то так

2024-04-05 07:15 UTC, vdromanov commented
> А можно не переходя в бутлодер считать сигнатуру? Я из скриншота не очень понял.
> 
> Ну и ещё накину, если можно: может добавить ещё чтение версии прошивки и версии загрузчика? А то простого способа их прочитать также нет. При этом версия прошивки доступна только из прошивки. Если девайс в загрузчике, можно вместо неё написать, что перейдите в прошивку для чтения версии прошивки. Ну и ключ назвать --get-dev-info или как-то так

а давайте через тикет, а то задача поступала - "считать сигнатуру прошивки"

читать можно и из бутлоадера, и из прошивки (собственно, поэтому так корявенько)

2024-04-05 07:58 UTC, pgasheev commented
Сделал тикет: https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/73444/

> а давайте через тикет, а то задача поступала - "считать сигнатуру прошивки"

Да, но вот оказалось с версией та же проблема что и сигнатурой

2024-04-07 17:33 UTC, vdromanov commented
поговорили с Сашей Дегтярёвым - решили сразу сделать хорошо, чтобы не менять апи потом

![image](https://github.com/wirenboard/wb-mcu-fw-flasher/assets/25829054/4f123e37-b5d0-4430-b597-15c34249fb49)

2024-04-10 04:29 UTC, KraPete requested changes

2024-04-10 04:29 UTC, KraPete commented on debian/changelog
> +wb-mcu-fw-flasher (1.3.3) stable; urgency=medium
Давай, minor увеличим, новая фича же

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +    const struct option long_options[] = {
Расскажи про логику наименования переменных где-то cameCase, где-то snake_case. Зачем?

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +    uint16_t fwSig[12];  // reading fw-sig is supported both in firmware and bootloader
Давай, эти 12 в константу завернём, а то оно много где используется

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +    char blVer[8];
Эту 8 тоже в константу бы

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +int readString(modbus_t *ctx, char *buf, int start_addr, int len){
Должна ли строка заканчиваться на `\0`?
Не надо ли это проверять?
Не надо ли контролировать выход за границы буфера, если надо `\0` добавлять?

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +    char fwVer[15];
И это в константу

2024-04-10 04:29 UTC, KraPete commented on flasher.c
> +    char fwSig[12];
Где-то я эти 12 уже видел

2024-04-21 22:44 UTC, vdromanov commented on debian/changelog
> +wb-mcu-fw-flasher (1.3.3) stable; urgency=medium
готово

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +    const struct option long_options[] = {
так бардак же: тулза писалась до появления у нас каких-то кодестайлов, вот никто и не следил

кодестайла на не-ембеддед с у нас нет => я почитал-подумал-посмотрел, чего здесь больше => переименовал на camelCase отдельным коммитом

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +int readString(modbus_t *ctx, char *buf, int start_addr, int len){
должна заканчиваться на \0

концептуально переделал

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +    uint16_t fwSig[12];  // reading fw-sig is supported both in firmware and bootloader
готово

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +    char blVer[8];
готово

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +    char fwVer[15];
готово

2024-04-21 22:44 UTC, vdromanov commented on flasher.c
> +    char fwSig[12];
готово

2024-04-22 03:55 UTC, KraPete requested changes

2024-04-22 03:55 UTC, KraPete commented on flasher.c
> +        buf[len] = "\0";
`buf[rc] = "\0"`
Прочитаешь меньше, будет мусор.

2024-04-22 03:55 UTC, KraPete commented on flasher.c
> +        modbus_t *readInfoConnection;
Я бы это всё вынес в отдельную функцию

2024-04-22 07:30 UTC, vdromanov commented on flasher.c
> +        buf[len] = "\0";
готово!

2024-04-22 07:30 UTC, vdromanov commented on flasher.c
> +        modbus_t *readInfoConnection;
там 8-9 параметров надо будет тащить в функцию => предлагаю забить

2024-04-22 08:16 UTC, KraPete approved these changes

2024-04-22 08:27 UTC, merged